/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateAaaArgs } from "./CreateAaaArgs";
import { UpdateAaaArgs } from "./UpdateAaaArgs";
import { DeleteAaaArgs } from "./DeleteAaaArgs";
import { AaaCountArgs } from "./AaaCountArgs";
import { AaaFindManyArgs } from "./AaaFindManyArgs";
import { AaaFindUniqueArgs } from "./AaaFindUniqueArgs";
import { Aaa } from "./Aaa";
import { AaaService } from "../aaa.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Aaa)
export class AaaResolverBase {
  constructor(
    protected readonly service: AaaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Aaa",
    action: "read",
    possession: "any",
  })
  async _aaasMeta(
    @graphql.Args() args: AaaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Aaa])
  @nestAccessControl.UseRoles({
    resource: "Aaa",
    action: "read",
    possession: "any",
  })
  async aaas(@graphql.Args() args: AaaFindManyArgs): Promise<Aaa[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Aaa, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Aaa",
    action: "read",
    possession: "own",
  })
  async aaa(@graphql.Args() args: AaaFindUniqueArgs): Promise<Aaa | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Aaa)
  @nestAccessControl.UseRoles({
    resource: "Aaa",
    action: "create",
    possession: "any",
  })
  async createAaa(@graphql.Args() args: CreateAaaArgs): Promise<Aaa> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Aaa)
  @nestAccessControl.UseRoles({
    resource: "Aaa",
    action: "update",
    possession: "any",
  })
  async updateAaa(@graphql.Args() args: UpdateAaaArgs): Promise<Aaa | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Aaa)
  @nestAccessControl.UseRoles({
    resource: "Aaa",
    action: "delete",
    possession: "any",
  })
  async deleteAaa(@graphql.Args() args: DeleteAaaArgs): Promise<Aaa | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
